# Generated by Django 4.2.7 on 2023-11-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_title',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
