# Generated by Django 4.2.7 on 2023-11-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_short_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=0, upload_to='post_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='short_title',
            field=models.CharField(max_length=50),
        ),
    ]
