# Generated by Django 4.2.7 on 2023-11-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_options_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='user_name',
            field=models.CharField(default=0, max_length=20, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
    ]
